include:
  project: utilities/ci-template
  file: gitlab-ci-base.yml

tests:
  stage: test
  rules:
    - if: '$CI_COMMIT_TITLE !~ /^\d+.\d+.\d+$/'
  script:
    - pip --cache-dir=.pip install --quiet .
    - pip --cache-dir=.pip install --quiet -r tests/requirements.txt
    - pytest --cov ntc tests/
  coverage: '/^TOTAL.+?(\d+\%)$/'
