---
include:
  - project: utilities/nt-dev
    file: nt_dev/release/gitlab-python-tests-basic.yml

test-mypy:
  extends: .common__tests_frozen
  script:
    - nt-mypy .

check-yamlfix:
  extends: .common__tests_frozen
  script:
    - nt-yamlfix --check
